openapi: 3.0.0
info:
  title: API for Products Service
  version: 1.0.0
  description: |
    API for Products Service

    ### Key Features
    - **Products:** Retrieval of Products information.
servers:
  - url: http://localhost:8080
    description: Local environment
paths:
  /products-services/products:
    get:
      summary: Gets info Products.
      description: Retrieves info Products.
      operationId: getProducts
      tags:
        - Products
      parameters:
        - $ref: '#/components/parameters/X-Product'
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad request
        '404':
          description: Product not found
        '412':
          description: Precondition failed
        '500':
          description: Internal server error
components:
  parameters:
    X-Product:
      name: x-product
      in: header
      description: Code product
      required: true
      schema:
        type: string
        example: "Name product"
  schemas:
    ProductResponse:
      type: object
      properties:
        numberOfProducts:
          type: integer
          example: 12
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductsDTO'
    ProductsDTO:
      type: object
      properties:
        productId:
          type: integer
          example: 1
        productName:
          type: string
          example: "Name Product"
        productPrice:
          type: number
          example: 12.34
        productDescription:
          type: string
          example: "Description Product"
        productCategory:
          type: string
          example: "Category Product"
        productImage:
          type: string
          example: "URL Image Product"